version: '3.3'
services:
  frontend:
    depends_on:
      - deploy
    build:
      context: ./dapp
      dockerfile: Dockerfile
    volumes:
      - './dapp/src:/app/src'
    ports:
      - 3000:3000

  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.deploy